server:
  port: 9991

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456

zuul:
  routes:
    feign-auth:
      path: /auth/**
      serviceId: crawler-auth
      strip-prefix: true
      custom-sensitive-headers: true
    feign-user:
      path: /user/**
      serviceId: crawler-goddess
      sensitiveHeaders:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9990/eureka/


logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO


#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:${server.port}/auth/oauth/token
#      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
#      client-id: android
#    resource:
#      user-info-uri: http://localhost:${server.port}/auth/user
#      prefer-token-info: false

ribbon:
  ReadTimeout: 6000000
  SocketTimeout: 6000000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000